# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plot(object):
    def setupUi(self, Plot):
        Plot.setObjectName("Plot")
        Plot.resize(562, 697)
        self.centralwidget = QtWidgets.QWidget(Plot)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 300, 541, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_run_event = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_run_event.setObjectName("lbl_run_event")
        self.gridLayout.addWidget(self.lbl_run_event, 0, 0, 1, 1)
        self.lbl_axis_units = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_axis_units.setObjectName("lbl_axis_units")
        self.gridLayout.addWidget(self.lbl_axis_units, 0, 15, 1, 1)
        self.tbox_c_axis_units = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_c_axis_units.setObjectName("tbox_c_axis_units")
        self.gridLayout.addWidget(self.tbox_c_axis_units, 4, 15, 1, 1)
        self.line_38 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.gridLayout.addWidget(self.line_38, 3, 14, 1, 1)
        self.tbox_min_event = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.tbox_min_event.setObjectName("tbox_min_event")
        self.gridLayout.addWidget(self.tbox_min_event, 2, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 4, 8, 1, 1)
        self.lbl_min_event = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_min_event.setObjectName("lbl_min_event")
        self.gridLayout.addWidget(self.lbl_min_event, 2, 0, 1, 1)
        self.lbl_run = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_run.setObjectName("lbl_run")
        self.gridLayout.addWidget(self.lbl_run, 1, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 4, 1, 1)
        self.lbl_c = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_c.setObjectName("lbl_c")
        self.gridLayout.addWidget(self.lbl_c, 4, 5, 1, 1)
        self.lbl_y = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_y.setObjectName("lbl_y")
        self.gridLayout.addWidget(self.lbl_y, 3, 5, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout.addWidget(self.line_20, 0, 12, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 2, 4, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 4, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 1, 9, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 4, 4, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout.addWidget(self.line_28, 4, 12, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 0, 10, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 4, 6, 1, 1)
        self.lbl_x = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_x.setObjectName("lbl_x")
        self.gridLayout.addWidget(self.lbl_x, 2, 5, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 6, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 5, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 2, 6, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 0, 8, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 0, 6, 1, 1)
        self.lbl_min = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_min.setObjectName("lbl_min")
        self.gridLayout.addWidget(self.lbl_min, 0, 7, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 3, 6, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 1, 8, 1, 1)
        self.lbl_max = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_max.setObjectName("lbl_max")
        self.gridLayout.addWidget(self.lbl_max, 0, 9, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 3, 8, 1, 1)
        self.lbl_axis_labels = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_axis_labels.setObjectName("lbl_axis_labels")
        self.gridLayout.addWidget(self.lbl_axis_labels, 0, 13, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout.addWidget(self.line_23, 1, 13, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 1, 11, 1, 1)
        self.lbl_num_ticks = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_num_ticks.setObjectName("lbl_num_ticks")
        self.gridLayout.addWidget(self.lbl_num_ticks, 0, 11, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout.addWidget(self.line_24, 1, 10, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout.addWidget(self.line_26, 3, 10, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout.addWidget(self.line_25, 2, 10, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout.addWidget(self.line_27, 4, 10, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout.addWidget(self.line_31, 1, 12, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout.addWidget(self.line_29, 3, 12, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout.addWidget(self.line_30, 2, 12, 1, 1)
        self.spinBox_x_num_ticks = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_x_num_ticks.setObjectName("spinBox_x_num_ticks")
        self.gridLayout.addWidget(self.spinBox_x_num_ticks, 2, 11, 1, 1)
        self.spinBox_z_num_ticks = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_z_num_ticks.setObjectName("spinBox_z_num_ticks")
        self.gridLayout.addWidget(self.spinBox_z_num_ticks, 4, 11, 1, 1)
        self.spinBox_y_num_ticks = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_y_num_ticks.setObjectName("spinBox_y_num_ticks")
        self.gridLayout.addWidget(self.spinBox_y_num_ticks, 3, 11, 1, 1)
        self.tbox_x_max = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_x_max.setObjectName("tbox_x_max")
        self.gridLayout.addWidget(self.tbox_x_max, 2, 9, 1, 1)
        self.tbox_x_min = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_x_min.setObjectName("tbox_x_min")
        self.gridLayout.addWidget(self.tbox_x_min, 2, 7, 1, 1)
        self.tbox_y_min = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_y_min.setObjectName("tbox_y_min")
        self.gridLayout.addWidget(self.tbox_y_min, 3, 7, 1, 1)
        self.tbox_c_min = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_c_min.setObjectName("tbox_c_min")
        self.gridLayout.addWidget(self.tbox_c_min, 4, 7, 1, 1)
        self.tbox_x_axis_labels = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_x_axis_labels.setObjectName("tbox_x_axis_labels")
        self.gridLayout.addWidget(self.tbox_x_axis_labels, 2, 13, 1, 1)
        self.lbl_live = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_live.setObjectName("lbl_live")
        self.gridLayout.addWidget(self.lbl_live, 4, 0, 1, 1)
        self.tbox_c_max = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_c_max.setObjectName("tbox_c_max")
        self.gridLayout.addWidget(self.tbox_c_max, 4, 9, 1, 1)
        self.tbox_y_max = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_y_max.setObjectName("tbox_y_max")
        self.gridLayout.addWidget(self.tbox_y_max, 3, 9, 1, 1)
        self.tbox_y_axis_labels = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_y_axis_labels.setObjectName("tbox_y_axis_labels")
        self.gridLayout.addWidget(self.tbox_y_axis_labels, 3, 13, 1, 1)
        self.tbox_c_axis_labels = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_c_axis_labels.setObjectName("tbox_c_axis_labels")
        self.gridLayout.addWidget(self.tbox_c_axis_labels, 4, 13, 1, 1)
        self.tbox_max_event = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_max_event.setObjectName("tbox_max_event")
        self.gridLayout.addWidget(self.tbox_max_event, 3, 1, 1, 1)
        self.lbl_max_event = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_max_event.setObjectName("lbl_max_event")
        self.gridLayout.addWidget(self.lbl_max_event, 3, 0, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout.addWidget(self.line_39, 2, 14, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout.addWidget(self.line_41, 0, 14, 1, 1)
        self.comboBox_run_event = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_run_event.setObjectName("comboBox_run_event")
        self.comboBox_run_event.addItem("")
        self.comboBox_run_event.addItem("")
        self.comboBox_run_event.addItem("")
        self.gridLayout.addWidget(self.comboBox_run_event, 0, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 2, 8, 1, 1)
        self.line_42 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.gridLayout.addWidget(self.line_42, 4, 14, 1, 1)
        self.tbox_y_axis_units = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_y_axis_units.setObjectName("tbox_y_axis_units")
        self.gridLayout.addWidget(self.tbox_y_axis_units, 3, 15, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout.addWidget(self.line_43, 1, 15, 1, 1)
        self.tbox_x_axis_units = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_x_axis_units.setObjectName("tbox_x_axis_units")
        self.gridLayout.addWidget(self.tbox_x_axis_units, 2, 15, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout.addWidget(self.line_40, 1, 14, 1, 1)
        self.tbox_num_shots_live = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_num_shots_live.setObjectName("tbox_num_shots_live")
        self.gridLayout.addWidget(self.tbox_num_shots_live, 4, 1, 1, 1)
        self.tbox_run = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_run.setObjectName("tbox_run")
        self.gridLayout.addWidget(self.tbox_run, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioBtn_histogram = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioBtn_histogram.setObjectName("radioBtn_histogram")
        self.gridLayout_3.addWidget(self.radioBtn_histogram, 2, 0, 1, 1)
        self.radioBtn_color = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioBtn_color.setObjectName("radioBtn_color")
        self.gridLayout_3.addWidget(self.radioBtn_color, 3, 0, 1, 1)
        self.radioBtn_scatter = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioBtn_scatter.setObjectName("radioBtn_scatter")
        self.gridLayout_3.addWidget(self.radioBtn_scatter, 1, 0, 1, 1)
        self.checkBox_subtraction = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_subtraction.setObjectName("checkBox_subtraction")
        self.gridLayout_3.addWidget(self.checkBox_subtraction, 2, 2, 1, 1)
        self.lbl_plot_type = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_plot_type.setObjectName("lbl_plot_type")
        self.gridLayout_3.addWidget(self.lbl_plot_type, 0, 0, 1, 1)
        self.btn_set_onoff_filter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_set_onoff_filter.setObjectName("btn_set_onoff_filter")
        self.gridLayout_3.addWidget(self.btn_set_onoff_filter, 3, 2, 1, 1)
        self.btn_change_filters = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_change_filters.setObjectName("btn_change_filters")
        self.gridLayout_3.addWidget(self.btn_change_filters, 1, 2, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_3.addWidget(self.line_34, 3, 1, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_3.addWidget(self.line_35, 2, 1, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_3.addWidget(self.line_32, 1, 1, 1, 1)
        self.btn_set_plot_var = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_set_plot_var.setObjectName("btn_set_plot_var")
        self.gridLayout_3.addWidget(self.btn_set_plot_var, 0, 2, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_3.addWidget(self.line_33, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.line_36 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.horizontalLayout_2.addWidget(self.line_36)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_current_plot_var = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_current_plot_var.setObjectName("lbl_current_plot_var")
        self.verticalLayout_2.addWidget(self.lbl_current_plot_var)
        self.lbl_current_filters = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_current_filters.setObjectName("lbl_current_filters")
        self.verticalLayout_2.addWidget(self.lbl_current_filters)
        self.lbl_current_onoff_filter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_current_onoff_filter.setObjectName("lbl_current_onoff_filter")
        self.verticalLayout_2.addWidget(self.lbl_current_onoff_filter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.btn_update = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_update.setObjectName("btn_update")
        self.verticalLayout.addWidget(self.btn_update)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_capture = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_capture.setObjectName("btn_capture")
        self.horizontalLayout.addWidget(self.btn_capture)
        self.lbl_captured_filename = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_captured_filename.setObjectName("lbl_captured_filename")
        self.horizontalLayout.addWidget(self.lbl_captured_filename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.replace_with_plot = QtWidgets.QGraphicsView(self.centralwidget)
        self.replace_with_plot.setGeometry(QtCore.QRect(10, 10, 541, 289))
        self.replace_with_plot.setMinimumSize(QtCore.QSize(541, 289))
        self.replace_with_plot.setMaximumSize(QtCore.QSize(541, 289))
        self.replace_with_plot.setObjectName("replace_with_plot")
        Plot.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Plot)
        self.statusbar.setObjectName("statusbar")
        Plot.setStatusBar(self.statusbar)

        self.retranslateUi(Plot)
        QtCore.QMetaObject.connectSlotsByName(Plot)

    def retranslateUi(self, Plot):
        _translate = QtCore.QCoreApplication.translate
        Plot.setWindowTitle(_translate("Plot", "Plotter"))
        self.lbl_run_event.setText(_translate("Plot", "range type"))
        self.lbl_axis_units.setText(_translate("Plot", "axis units"))
        self.lbl_min_event.setText(_translate("Plot", "min event"))
        self.lbl_run.setText(_translate("Plot", "run"))
        self.lbl_c.setText(_translate("Plot", "c"))
        self.lbl_y.setText(_translate("Plot", "y"))
        self.lbl_x.setText(_translate("Plot", "x"))
        self.lbl_min.setText(_translate("Plot", "min"))
        self.lbl_max.setText(_translate("Plot", "max"))
        self.lbl_axis_labels.setText(_translate("Plot", "axis labels"))
        self.lbl_num_ticks.setText(_translate("Plot", "# ticks"))
        self.lbl_live.setText(_translate("Plot", "num shots live"))
        self.lbl_max_event.setText(_translate("Plot", "max event"))
        self.comboBox_run_event.setItemText(0, _translate("Plot", "run"))
        self.comboBox_run_event.setItemText(1, _translate("Plot", "events"))
        self.comboBox_run_event.setItemText(2, _translate("Plot", "live"))
        self.radioBtn_histogram.setText(_translate("Plot", "histogram"))
        self.radioBtn_color.setText(_translate("Plot", "color"))
        self.radioBtn_scatter.setText(_translate("Plot", "scatter"))
        self.checkBox_subtraction.setText(_translate("Plot", "subtraction?"))
        self.lbl_plot_type.setText(_translate("Plot", "Plot type:"))
        self.btn_set_onoff_filter.setText(_translate("Plot", "set on/off filter"))
        self.btn_change_filters.setText(_translate("Plot", "change filters"))
        self.btn_set_plot_var.setText(_translate("Plot", "set plot variables"))
        self.lbl_current_plot_var.setText(_translate("Plot", "current plot variables"))
        self.lbl_current_filters.setText(_translate("Plot", "current filters"))
        self.lbl_current_onoff_filter.setText(_translate("Plot", "current on/off filter"))
        self.btn_update.setText(_translate("Plot", "update"))
        self.btn_capture.setText(_translate("Plot", "capture"))
        self.lbl_captured_filename.setText(_translate("Plot", "captured filename"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Plot = QtWidgets.QMainWindow()
    ui = Ui_Plot()
    ui.setupUi(Plot)
    Plot.show()
    sys.exit(app.exec_())

