# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roi_set.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_specify_rois = QtWidgets.QLabel(self.centralwidget)
        self.lbl_specify_rois.setGeometry(QtCore.QRect(40, 30, 221, 16))
        self.lbl_specify_rois.setObjectName("lbl_specify_rois")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 371, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_name.setMinimumSize(QtCore.QSize(150, 0))
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout.addWidget(self.lbl_name)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.lbl_x1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_x1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_x1.setObjectName("lbl_x1")
        self.horizontalLayout.addWidget(self.lbl_x1)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.lbl_x2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_x2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_x2.setObjectName("lbl_x2")
        self.horizontalLayout.addWidget(self.lbl_x2)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.lbl_y1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_y1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_y1.setObjectName("lbl_y1")
        self.horizontalLayout.addWidget(self.lbl_y1)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.lbl_y2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_y2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_y2.setObjectName("lbl_y2")
        self.horizontalLayout.addWidget(self.lbl_y2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbox_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tbox_name.setMinimumSize(QtCore.QSize(150, 0))
        self.tbox_name.setObjectName("tbox_name")
        self.horizontalLayout_2.addWidget(self.tbox_name)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.tbox_x1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tbox_x1.setObjectName("tbox_x1")
        self.horizontalLayout_2.addWidget(self.tbox_x1)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.tbox_x2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tbox_x2.setObjectName("tbox_x2")
        self.horizontalLayout_2.addWidget(self.tbox_x2)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.line_7)
        self.tbox_y1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tbox_y1.setObjectName("tbox_y1")
        self.horizontalLayout_2.addWidget(self.tbox_y1)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.tbox_y2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tbox_y2.setObjectName("tbox_y2")
        self.horizontalLayout_2.addWidget(self.tbox_y2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_10 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout.addWidget(self.line_10)
        self.lbl_current_roi = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_current_roi.setObjectName("lbl_current_roi")
        self.verticalLayout.addWidget(self.lbl_current_roi)
        self.tbox_current_roi = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.tbox_current_roi.setReadOnly(True)
        self.tbox_current_roi.setObjectName("tbox_current_roi")
        self.verticalLayout.addWidget(self.tbox_current_roi)
        self.btn_add_roi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_roi.sizePolicy().hasHeightForWidth())
        self.btn_add_roi.setSizePolicy(sizePolicy)
        self.btn_add_roi.setObjectName("btn_add_roi")
        self.verticalLayout.addWidget(self.btn_add_roi)
        self.btn_remove_roi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remove_roi.sizePolicy().hasHeightForWidth())
        self.btn_remove_roi.setSizePolicy(sizePolicy)
        self.btn_remove_roi.setObjectName("btn_remove_roi")
        self.verticalLayout.addWidget(self.btn_remove_roi)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Set ROIs"))
        self.lbl_specify_rois.setText(_translate("MainWindow", "Specify ROI\'s"))
        self.lbl_name.setText(_translate("MainWindow", "Name"))
        self.lbl_x1.setText(_translate("MainWindow", "x1"))
        self.lbl_x2.setText(_translate("MainWindow", "x2"))
        self.lbl_y1.setText(_translate("MainWindow", "y1"))
        self.lbl_y2.setText(_translate("MainWindow", "y2"))
        self.lbl_current_roi.setText(_translate("MainWindow", "Current ROI\'s"))
        self.btn_add_roi.setText(_translate("MainWindow", "Add"))
        self.btn_remove_roi.setText(_translate("MainWindow", "Remove"))

