# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roiSetter.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1416, 1487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plot = QtWidgets.QWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(70, 20, 1281, 1141))
        self.plot.setObjectName("plot")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(190, 1170, 1051, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_detector = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_detector.setObjectName("lbl_detector")
        self.verticalLayout.addWidget(self.lbl_detector)
        self.tbox_detector = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tbox_detector.setMinimumSize(QtCore.QSize(800, 0))
        self.tbox_detector.setObjectName("tbox_detector")
        self.verticalLayout.addWidget(self.tbox_detector)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioBtn_live = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioBtn_live.setObjectName("radioBtn_live")
        self.verticalLayout_2.addWidget(self.radioBtn_live)
        self.radioBtn_run = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioBtn_run.setObjectName("radioBtn_run")
        self.verticalLayout_2.addWidget(self.radioBtn_run)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tbox_num_shots_live = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tbox_num_shots_live.setPlaceholderText("")
        self.tbox_num_shots_live.setObjectName("tbox_num_shots_live")
        self.gridLayout.addWidget(self.tbox_num_shots_live, 0, 1, 1, 1)
        self.lbl_num_shots_live = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_num_shots_live.setObjectName("lbl_num_shots_live")
        self.gridLayout.addWidget(self.lbl_num_shots_live, 0, 0, 1, 1)
        self.lbl_run = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lbl_run.setObjectName("lbl_run")
        self.gridLayout.addWidget(self.lbl_run, 1, 0, 1, 1)
        self.tbox_run = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tbox_run.setObjectName("tbox_run")
        self.gridLayout.addWidget(self.tbox_run, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.btn_run_plot = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_run_plot.setObjectName("btn_run_plot")
        self.verticalLayout_3.addWidget(self.btn_run_plot)
        self.lbl_names = QtWidgets.QLabel(self.centralwidget)
        self.lbl_names.setGeometry(QtCore.QRect(190, 1430, 1051, 31))
        self.lbl_names.setObjectName("lbl_names")
        self.btn_stop_plot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop_plot.setGeometry(QtCore.QRect(190, 1280, 1049, 23))
        self.btn_stop_plot.setObjectName("btn_stop_plot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(790, 1330, 161, 31))
        self.label.setObjectName("label")
        self.plainTextEditReferenceDet = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditReferenceDet.setGeometry(QtCore.QRect(930, 1320, 311, 41))
        self.plainTextEditReferenceDet.setObjectName("plainTextEditReferenceDet")
        self.plainTextEditBeamline = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditBeamline.setGeometry(QtCore.QRect(350, 1320, 311, 41))
        self.plainTextEditBeamline.setObjectName("plainTextEditBeamline")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 1330, 161, 31))
        self.label_2.setObjectName("label_2")
        self.pushButtonUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdate.setGeometry(QtCore.QRect(191, 1380, 1051, 23))
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tbox_detector, self.radioBtn_live)
        MainWindow.setTabOrder(self.radioBtn_live, self.radioBtn_run)
        MainWindow.setTabOrder(self.radioBtn_run, self.tbox_num_shots_live)
        MainWindow.setTabOrder(self.tbox_num_shots_live, self.tbox_run)
        MainWindow.setTabOrder(self.tbox_run, self.btn_run_plot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Detector Viewer"))
        self.lbl_detector.setText(_translate("MainWindow", "Detector"))
        self.radioBtn_live.setText(_translate("MainWindow", "Live"))
        self.radioBtn_run.setText(_translate("MainWindow", "Run"))
        self.lbl_num_shots_live.setText(_translate("MainWindow", "# Shots"))
        self.lbl_run.setText(_translate("MainWindow", "Run #"))
        self.btn_run_plot.setText(_translate("MainWindow", "Run"))
        self.lbl_names.setText(_translate("MainWindow", "Created by Matt Ware, Jordan O\'Neal, Kathryn Ledbetter, and Takahiro Sato\n"
"See readme for License info."))
        self.btn_stop_plot.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Reference Detector:"))
        self.label_2.setText(_translate("MainWindow", "Beamline:"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Update"))

